// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Googlesvc
{
public static class Test
{
        public const string achievement_3 = "CgkIlbe2-JMNEAIQAw"; // <GPGSID>
        public const string achievement_4 = "CgkIlbe2-JMNEAIQBA"; // <GPGSID>
        public const string achievement_5 = "CgkIlbe2-JMNEAIQCA"; // <GPGSID>
        public const string achievement__25_2 = "CgkIlbe2-JMNEAIQEw"; // <GPGSID>
        public const string achievement__20_2 = "CgkIlbe2-JMNEAIQEg"; // <GPGSID>
        public const string achievement_15 = "CgkIlbe2-JMNEAIQCw"; // <GPGSID>
        public const string leaderboard = "CgkIlbe2-JMNEAIQBg"; // <GPGSID>
        public const string achievement__30_2 = "CgkIlbe2-JMNEAIQFA"; // <GPGSID>
        public const string achievement_10 = "CgkIlbe2-JMNEAIQCg"; // <GPGSID>
        public const string achievement__30 = "CgkIlbe2-JMNEAIQDg"; // <GPGSID>
        public const string achievement_5_2 = "CgkIlbe2-JMNEAIQCQ"; // <GPGSID>
        public const string achievement__20 = "CgkIlbe2-JMNEAIQDA"; // <GPGSID>
        public const string leaderboard_2 = "CgkIlbe2-JMNEAIQBw"; // <GPGSID>
        public const string achievement__25 = "CgkIlbe2-JMNEAIQDQ"; // <GPGSID>
        public const string achievement__10 = "CgkIlbe2-JMNEAIQEA"; // <GPGSID>
        public const string achievement__5 = "CgkIlbe2-JMNEAIQDw"; // <GPGSID>
        public const string achievement__15 = "CgkIlbe2-JMNEAIQEQ"; // <GPGSID>
        public const string achievement = "CgkIlbe2-JMNEAIQAA"; // <GPGSID>
        public const string achievement_1 = "CgkIlbe2-JMNEAIQAQ"; // <GPGSID>
        public const string achievement_2 = "CgkIlbe2-JMNEAIQAg"; // <GPGSID>

}
}
